version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: ucount-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: ucount-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  activemq:
    image: rmohr/activemq:5.15.9
    container_name: ucount-activemq
    ports:
      - "61616:61616"
      - "8161:8161"

  user-onboarding-service:
    build:
      context: ../
      dockerfile: user-onboarding-service/Dockerfile
    container_name: ucount-onboarding-svc
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVICES_ACCESS_DECISION_SERVICE_URL: http://access-decision-service:8082
    depends_on:
      - kafka

  access-decision-service:
    build:
      context: ../
      dockerfile: access-decision-service/Dockerfile
    container_name: ucount-access-svc
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  notification-audit-service:
    build:
      context: ../
      dockerfile: notification-audit-service/Dockerfile
    container_name: ucount-notification-svc
    ports:
      - "8083:8083"
    environment:
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
    depends_on:
      - activemq
