server:
  port: 8083

spring:
  application:
    name: notification-audit-service

  datasource:
    url: jdbc:h2:mem:ucount_audit_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  activemq:
    broker-url: vm://localhost?broker.persistent=false
    in-memory: true
    pool:
      enabled: false

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
